### ISSUE TITLE
Add content that explains generally how absentee voting works (beneath the headline)

### ISSUE THREAD

**Issue by cogpark** [cogpark/participation_nation#35]
Here's what I deleted:

` <div className='row'>
                    <div className='col-md-6'>
                        <p>In many states, you can vote by mail or in person before Election Day. 
                        </p>
                <ul>
                    <li>Some Absentee vs. earl if a state doesn't list requirements, we just call it "early"</li>
                    <li>In most states, you'll follow this procedure: Fill out an absentee ballot request application, send it to your local election official, get a ballot in the mail, and send it back by election day</li>
                </ul>`

**Comment by thersites-ac** [comment]
Hey, just saw some recent commits, and I wanted to throw out some comments before you go too deep with the JSON files:

1:
```
"in_person_instructions": "Visit <a href='http://www.elections.alaska.gov/Core/AIPEVEvents.php'>an early/in-person absentee voting location</a> starting 15 days before the election."
```

The HTML in here is a perfect  use case for a react component. You'd probably want to restructure it something like as follows--
```
"in_person_instructions" : {
    "url": "http://www.elections.alaska.gov/Core/AIPEVEvents.php",
    "deadline": "15 days before election"
}
```

This goes inside e.g. an ```<Instructions />``` component which assembles text on the fly based on the content/structure of the object.


2:
The JSON data is getting pretty intense, and I think just from an organizational standpoint, it will soon become simpler to store it in a database. Non-relational might be easiest since it seems like internal structure of the information you're collecting right now is still somewhat in flux. I've looked into getting them connected and it's easy. From a coding perspective, this will also remove the need to slice up the JSON files you're generating and pass bits around from component to component; instead each can query the DB (or actually, talk to the backend api, which does the querying).

**Comment by cogpark** [comment]
1. That's pretty much what I did! It all fits using scorecards -- check the site now, since I pushed that live last night. (I am opening to further restructuring, but for now, I think it's MVP.)

2. It is, yes. I expect absentee will be the worst of it. The next project (ID requirements) will be just a bunch of <ul> elements. Still, I am opening to adding a db if you want to lead the charge there!
